### ISSUE TITLE
Readjust content of `HomologicalMethods.gd/gi` to PreSheaves

### ISSUE THREAD

**Issue by mohamed-barakat** [mohamed-barakat/FunctorCategories#189]
* Readjust content of `HomologicalMethods.gd/gi` to PreSheaves
* adapt the [code for enough projectives/injectives](https://github.com/homalg-project/FunctorCategories/blob/b520508f955b2c2eaf1d8f72d0ab64ecf0887649/gap/FunctorCategories.gi#L639-L659) to PreSheaves and relocate it from `FunctorCategories.gi` to `PreSheaves.gi`.

**Comment by kamalsaleh** [comment]
I think this issue can be closed by https://github.com/homalg-project/FunctorCategories/pull/222 and https://github.com/homalg-project/FunctorCategories/pull/176

**Comment by mohamed-barakat** [comment]
Yes, completed with #22 and #176.
